
`define RICOSOC_RAM_START_ADDR          32'h0000_0000
`define RICOSOC_INTRAM_END_ADDR         32'h00FF_FFFF
`define RICOSOC_EXTRAM_END_ADDR         32'h00FF_FFFF
`define RICOSOC_RAM_END_ADDR            32'h00FF_FFFF

`define RICOSOC_ROM_START_ADDR          32'h0100_0000
`define RICOSOC_ROM_END_ADDR            32'h0100_FFFF
`define RICOSOC_EXTFLASH_START_ADDR     32'h0101_0000
`define RICOSOC_EXTFLASH_END_ADDR       32'h01FF_FFFF

`define RICOSOC_PERIPH_START_ADDR       32'h0200_0000
`define RICOSOC_PERIPH_PAGE_SIZE        32'h0200_0100

`define RICOSOC_UART0_PERIPH_NUM        0
`define RICOSOC_UART0_BASE_ADDR         RICOSOC_PERIPH_START_ADDR + (RICOSOC_PERIPH_PAGE_SIZE * RICOSOC_UART0_PERIPH_NUM)
`define RICOSOC_UARTx_CLKDIV_ADDR       8'h00
`define RICOSOC_UARTx_DATA_ADDR         8'h04

`define RICOSOC_GPIO0_PERIPH_NUM        1
`define RICOSOC_GPIO0_BASE_ADDR         RICOSOC_PERIPH_START_ADDR + (RICOSOC_GPIO0_PERIPH_NUM * RICOSOC_UART0_PERIPH_NUM)
`define RICOSOC_GPIO0_PERIPH_NUM        2
`define RICOSOC_GPIO1_BASE_ADDR         RICOSOC_PERIPH_START_ADDR + (RICOSOC_GPIO0_PERIPH_NUM * RICOSOC_UART0_PERIPH_NUM)
`define RICOSOC_GPIOx_PORT_ADDR         8'h00
`define RICOSOC_GPIOx_DDR_ADDR          8'h04
`define RICOSOC_GPIOx_MODE_ADDR         8'h08

`define RICOSOC_PERIPH_END_ADDR         32'h02FF_FFFF

`define UART0_CLKDIV_ADDR               (RICOSOC_UART0_BASE_ADDR + RICOSOC_UARTx_CLKDIV_ADDR)
`define UART0_DATA_ADDR                 (RICOSOC_UART0_BASE_ADDR + RICOSOC_UARTx_DATA_ADDR)

`define GPIO0_PORT_ADDR                 (RICOSOC_GPIO0_BASE_ADDR + RICOSOC_GPIOx_PORT_ADDR)
`define GPIO0_DDR_ADDR                  (RICOSOC_GPIO0_BASE_ADDR + RICOSOC_GPIOx_DDR_ADDR)
`define GPIO0_MODE_ADDR                 (RICOSOC_GPIO0_BASE_ADDR + RICOSOC_GPIOx_MODE_ADDR)

`define GPIO1_PORT_ADDR                 (RICOSOC_GPIO1_BASE_ADDR + RICOSOC_GPIOx_PORT_ADDR)
`define GPIO1_DDR_ADDR                  (RICOSOC_GPIO1_BASE_ADDR + RICOSOC_GPIOx_DDR_ADDR)
`define GPIO1_MODE_ADDR                 (RICOSOC_GPIO1_BASE_ADDR + RICOSOC_GPIOx_MODE_ADDR)

`define UART0_DATA_ADDR                 (RICOSOC_GPIO0_BASE_ADDR + RICOSOC_UARTx_CLKDIV_ADDR)